<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <RootNamespace>Wooly.Core</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Devlooped.CredentialManager" />
    <PackageReference Include="Mastonet" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Http" />
    <PackageReference Include="Tomlyn" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Wooly.Tests" />
  </ItemGroup>

</Project>
