namespace Wooly.Core.Posts;

/// <summary>
///     What an instance made of a link the author already wrote into a post — a title, a site name, sometimes a picture
///     (CONTEXT.md's <b>Link preview</b>). Distinct from a <see cref="PostMedia" />, which is something the author
///     attached besides the text: this is generated by the instance from the text itself, so it is a field of its own on
///     <see cref="Post" /> rather than a kind of attachment (ADR-0018).
///     <para>
///         Only what a terminal can use is carried. The wire's <c>type</c>, <c>html</c>, <c>embed_url</c>, <c>width</c>,
///         <c>height</c> and <c>blurhash</c> exist to embed an iframe player, which nothing here can render, and
///         <c>author_url</c> is dropped so that a post never carries three things reaching for the same handful of
///         places (ADR-0018).
///     </para>
/// </summary>
public sealed record LinkPreview
{
    /// <summary>
    ///     Where the preview points — usually an address the post's own text already reaches, and openable anyway,
    ///     because a title and a description are a pointer to the article rather than the article itself and a reader
    ///     who wants it needs something to press <c>⏎</c> on (ADR-0018).
    /// </summary>
    public required string Url { get; init; }

    /// <summary>
    ///     What the page calls itself, or <see langword="null" /> where the instance made nothing of it — the wire says
    ///     "no title" with an empty string, the same way it says "no warning" on a post.
    /// </summary>
    public string? Title { get; init; }

    /// <summary>What the page says it is about, or <see langword="null" /> where the instance offered none.</summary>
    public string? Description { get; init; }

    /// <summary>
    ///     The site it is on, as the site names itself, or <see langword="null" /> where the instance offered none.
    ///     Worth carrying apart from <see cref="Url" />: a reader deciding whether to open something is told the site by
    ///     name rather than left to read it out of a host.
    /// </summary>
    public string? ProviderName { get; init; }

    /// <summary>
    ///     Where the picture the instance chose for the link is, or <see langword="null" /> where it chose none. Drawn
    ///     the way an attachment's picture is, and linked where a terminal cannot draw one (ADR-0016).
    /// </summary>
    public string? Image { get; init; }

    /// <summary>
    ///     Who the page says wrote it, or <see langword="null" /> where it says nothing. Shown as plain byline text the
    ///     same way <see cref="Post.Author" /> is, and never a reference of its own: their address usually differs from
    ///     <see cref="Url" /> and rarely matters enough to open, which is where consistency with attachments stops being
    ///     the stronger argument (ADR-0018).
    /// </summary>
    public string? Author { get; init; }
}
